Changed requires_model_validation to True
This causes errors in models to be thrown earlier, which produces
readable errors instead of

TypeError: run_tests() takes at least 1 non-keyword argument (0 given)